# Docker role
- hosts: "k8sMasters, k8sWorkers"
  remote_user: admin
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh
  roles:
    - installDocker

# Kubernetes role
- hosts: "k8sMasters, k8sWorkers"
  remote_user: admin
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh
  roles:
    - installKubernetes

# master role
- hosts: k8sMasters
  remote_user: admin
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh
  roles:
    - setMaster

# worker role
- hosts: k8sMasters
  remote_user: admin
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh
  tasks:
   - name: Create token to join cluster
     shell: kubeadm token create --print-join-command
     register: join_command_raw

   - name: Set join command as fact
     set_fact:
       join_command: "{{ join_command_raw.stdout_lines[0] }}"


- hosts: k8sWorkers
  remote_user: admin
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh
  tasks:
    - name: Join the cluster. Use log to prevent joining twice
      shell: "{{ hostvars['kubernetes'].join_command }} >> node_join.log"
      args:
        chdir: $HOME
        creates: node