---
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw
      tags:
         - masterJoinCommand

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"
      tags:
         - masterJoinCommand

    - name: join cluster
      shell: "{{ hostvars['k8sMasters'].join_command }} >> node_joined.txt"
      args:
        creates: node_joined.txt
      tags:
         - workerJoinCommand